plugin:
    name: 'wpjscc.api::lang.plugin.name'
    description: 'wpjscc.api::lang.plugin.description'
    author: wpjscc
    icon: wn-icon-ship
    replaces: {  }
permissions:
    wpjscc.api.tests:
        tab: Api
        label: 'Api demo'
navigation:
    tests:
        label: ApiDemo
        url: wpjscc/api/tests
        icon: icon-life-ring
        permissions:
            - wpjscc.api.tests
