# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'wpjscc.api::lang.models.test.label'

# Model Form Field configuration
form: $/wpjscc/api/models/test/fields_api.yaml

# Model Class name
modelClass: Wpjscc\Api\Models\Test

# Default redirect location
defaultRedirect: wpjscc/api/testsapi

# Create page
create:
    title: backend::lang.form.create_title
    redirect: wpjscc/api/testsapi/update/:id
    redirectClose: wpjscc/api/testsapi

# Update page
update:
    title: backend::lang.form.update_title
    redirect: wpjscc/api/testsapi
    redirectClose: wpjscc/api/testsapi

# Preview page
preview:
    title: backend::lang.form.preview_title
